name = "load_simple"
type = "logic"
xrml = '''
<?load file="components/header.hrml"?>
'''
expected = '''
<header>H</header>
'''

[[files]]
path = "components/header.hrml"
content = '''
<header>H</header>
'''
